### ISSUE TITLE
Why you no sleep?

### ISSUE THREAD

**Issue by garyng** [Raymai97/libStrOfInt#1]
Sleeepppppp 🤣

**Edit**: I think GitHub is broken?
![image](https://user-images.githubusercontent.com/4453664/49464553-25bf0c00-f836-11e8-8671-4f7563284497.png)

**Comment by Raymai97** [comment]
lol was experimenting with git submodule, this repo is totally unstable, i mean, i intentionally "git push -f" to test stuff...
